# Generated by Django 5.0.2 on 2024-04-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_event_logement_recommandation_stage_tronsport_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tronsport',
            new_name='Transport',
        ),
    ]
