# Generated by Django 5.0.2 on 2024-04-20 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_socite_stage_societe_transport_datedepart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='datedepart',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
