# Generated by Django 5.0.4 on 2024-05-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='nbrSieges',
            field=models.IntegerField(default=4),
        ),
    ]
