# Generated by Django 5.0.4 on 2024-05-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_transport_nbrsieges'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.TextField(default='hhh'),
            preserve_default=False,
        ),
    ]
