# Generated by Django 5.0.4 on 2024-05-09 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_post_nbrpersonne_alter_transport_nbrsieges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='reservation',
            name='notificated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
