# Generated by Django 5.0.4 on 2024-05-09 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_reservation_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='notificated_at',
        ),
    ]
