# Generated by Django 5.0.4 on 2024-05-09 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_reservation_notificated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservate_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
