# Generated by Django 5.0.3 on 2024-04-02 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notificated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
