# Generated by Django 5.0.3 on 2024-04-19 09:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_notification_notificated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.post')),
                ('intitule', models.TextField()),
                ('description', models.TextField()),
                ('lieu', models.TextField()),
                ('contactInfo', models.TextField()),
            ],
            bases=('account.post',),
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.post')),
                ('localisation', models.TextField()),
                ('description', models.TextField()),
                ('contactInfo', models.TextField()),
            ],
            bases=('account.post',),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.post')),
                ('text', models.TextField()),
            ],
            bases=('account.post',),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.post')),
                ('typeStg', models.IntegerField(default=1)),
                ('socite', models.TextField()),
                ('duree', models.IntegerField(default=1)),
                ('sujet', models.TextField()),
                ('contactInfo', models.TextField()),
                ('specialite', models.TextField()),
            ],
            bases=('account.post',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.post')),
                ('depart', models.TextField()),
                ('destination', models.TextField()),
                ('heureDep', models.DateField(default=datetime.datetime.today)),
                ('nbrSieges', models.IntegerField(default=1)),
                ('contactInfo', models.TextField()),
            ],
            bases=('account.post',),
        ),
        migrations.CreateModel(
            name='EventClub',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.event')),
                ('club', models.TextField()),
            ],
            bases=('account.event',),
        ),
        migrations.CreateModel(
            name='EventSocial',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.event')),
                ('prix', models.FloatField(default=0.0)),
            ],
            bases=('account.event',),
        ),
    ]
