# Generated by Django 5.0.3 on 2024-04-28 15:03

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_event_logement_recommandation_stage_transport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='socite',
            new_name='societe',
        ),
        migrations.AddField(
            model_name='transport',
            name='datedepart',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transport',
            name='heureDep',
            field=models.IntegerField(default=12),
        ),
    ]
