# Generated by Django 5.0.3 on 2024-04-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_socite_stage_societe_transport_datedepart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
