# Generated by Django 5.0.3 on 2024-03-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_profile_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='enter bio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(blank=True, default='enter first name ', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(blank=True, default='enter last name', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='enter location', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.IntegerField(blank=True, default=12345678),
        ),
        migrations.AddField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images/%y/%m/%d'),
        ),
    ]
