# Generated by Django 5.0.3 on 2024-03-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_profile_bio_profile_firstname_profile_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastName',
        ),
    ]
