# Generated by Django 5.0.3 on 2024-03-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_remove_profile_firstname_remove_profile_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='utilisateur',
            field=models.IntegerField(default=2),
        ),
    ]
