# Generated by Django 5.0.2 on 2024-04-14 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(default=uuid.uuid4)),
                ('phoneNumber', models.IntegerField(blank=True, default=216)),
                ('bio', models.TextField(blank=True, default='')),
                ('utilisateur', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('profileimg', models.ImageField(default='blank-profile-picture.png', upload_to='profile_images/%y/%m/%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
